#!/usr/bin/env python3
"""美的风扇灯 ESPHome 配置生成器"""
import json

def load_devices():
    with open("devices.json","r",encoding="utf-8") as f: return json.load(f)

def gen_header(c):
    return f"""# Auto-generated by generate.py
substitutions:
  project_name: "{c['project_name']}"
  build_time: "Unknown"

esphome:
  name: ble-2
  friendly_name: "${{project_name}}"
  includes: [midea_ble_controller.h]

esp32:
  board: esp32dev; flash_size: 4MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y; CONFIG_BT_ENABLED: y; CONFIG_BT_BLE_ENABLED: y

logger: { baud_rate: 0; level: INFO }

wifi:
  ssid: "{c['wifi_ssid']}"; password: "{c['wifi_password']}"
  fast_connect: true; power_save_mode: none
  ap: {{ ssid: "BLE-GW Fallback"; password: "12345678" }}

captive_portal:
web_server: { port: 80 }
ota: [platform: esphome]
api:
  reboot_timeout: 0s
  services:
    - service: send_raw_hex
      variables: {{ hex_data: string }}
      then: [lambda: 'id(tx).send_hex(hex_data);']

external_components: [source: {{ type: local; path: components }}]

ble_tx: { id: tx }
esp32_ble: { io_capability: none; enable_on_boot: true }
bluetooth_proxy: { active: true; cache_services: true }
"""

def gen_globals(d):
    r="globals:\n"
    for x in d: r+=f"  - id: {x['name'].lower()}_ct_kelvin\n    type: int\n    restore_value: no\n    initial_value: '4600'\n"
    return r

def gen_mqtt(c,d):
    r=f"""mqtt:
  id: bemfa; broker: bemfa.com; port: 9501
  username: "{c['bemfa_uid']}"; password: "{c['bemfa_uid']}"; client_id: "{c['bemfa_uid']}"
  keepalive: 30s; discovery: false; birth_message:; will_message:
  on_message:
"""
    for x in d:
        n=x['name'].lower(); m=x['mac']; lt=x['bemfa_light_topic']; ft=x['bemfa_fan_topic']
        r+=f"""    - topic: "{lt}"
      then:
        - lambda: |-
            if(x=="on"){{ int ct=id({n}_ct_kelvin),brt=id({n}_brt).state; if(brt<1)brt=50; id(tx).send_hex(midea_light_on("{m}",brt,ct)); id({n}_light_on).publish_state(true); }}
            else if(x=="off"){{ id(tx).send_hex(midea_light_off("{m}")); id({n}_light_on).publish_state(false); }}
            else if(x.find("on#")==0){{ auto r=x.substr(3); auto p=r.find('#'); int brt=std::stoi(r.substr(0,p)),ct=id({n}_ct_kelvin);
              if(p!=std::string::npos){{ auto s=r.substr(p+1); if(!s.empty()){{ int pc=std::stoi(s); if(pc>=2700&&pc<=6500){{ct=pc;id({n}_ct_kelvin)=ct;}}}}}}
              id(tx).send_hex(midea_light_on("{m}",brt,ct)); id({n}_light_on).publish_state(true); }}
    - topic: "{ft}"
      then:
        - lambda: |-
            if(x=="on"){{ int spd=id({n}_spd).state; if(spd<1)spd=1; id(tx).send_hex(midea_fan_on("{m}",spd)); id({n}_fan_on).publish_state(true); }}
            else if(x=="off"){{ id(tx).send_hex(midea_fan_off("{m}")); id({n}_fan_on).publish_state(false); }}
            else if(x.find("on#")==0){{ int s=std::stoi(x.substr(3)); id(tx).send_hex(midea_fan_on("{m}",s)); id({n}_fan_on).publish_state(true); }}
"""
    return r

def gen_ble(d):
    r="""esp32_ble_tracker:
  scan_parameters: { interval: 640ms; window: 30ms; active: false }
  on_ble_advertise:
    - then:
        - lambda: |-
            auto datas=x.get_manufacturer_datas();
            for(auto&data:datas){auto&raw=data.data; if(raw.size()<20)continue;
"""
    for x in d:
        n=x['name'].lower(); m=x['mac']; lt=x['bemfa_light_topic']; ft=x['bemfa_fan_topic']
        mb=", ".join([f"0x{m[i:i+2]}" for i in range(0,12,2)])
        r+=f"""              uint8_t {n}_mac[6]={{{mb}}};
              for(int i=2;i<=(int)raw.size()-6;i++){{ if(memcmp(&raw[i],{n}_mac,6)==0){{
                bool lo=(raw[i+7]==0x01); int br=(int)(raw[i+12]/255.0f*100.0f);
                int ct=2700+(6500-2700)*(int)(raw[i+13]/255.0f*100.0f)/100;
                uint8_t fs=raw[i+16]; bool fr=(fs&0x01)!=0; int sp=fr?(raw[i+17]+1):0;
                static bool ll=false,lfr=false; static int lb=-1,lc=-1,lfs=-1;
                static uint32_t lr=0,lch=0; static uint8_t rc=0;
                bool ch=(lo!=ll)||(br!=lb)||(ct!=lc)||(fr!=lfr)||(sp!=lfs);
                if(ch){{lch=millis();rc=0;ll=lo;lb=br;lc=ct;lfr=fr;lfs=sp;}}
                bool hb=(millis()-lr>60000),rt=(millis()-lch<10000)&&(rc<3)&&(millis()-lr>3000);
                if(ch||hb||rt){{ if(rt)rc++;else rc=0; lr=millis();
                  if(lo)id(bemfa).publish("{lt}/up","on#"+std::to_string(br)+"#"+std::to_string(ct));
                  else id(bemfa).publish("{lt}/up","off");
                  if(fr)id(bemfa).publish("{ft}/up","on#"+std::to_string(sp));
                  else id(bemfa).publish("{ft}/up","off");
                  id({n}_light_on).publish_state(lo); id({n}_brt).publish_state(br);
                  id({n}_ct).publish_state(ct); id({n}_fan_on).publish_state(fr);
                  id({n}_spd).publish_state(sp);
                  id({n}_light).publish_state(lo); id({n}_light).publish_brightness(br/100.0f);
                  id({n}_light).publish_color_temperature(1000000.0f/ct);
                  id({n}_fan).publish_state(fr); id({n}_fan).publish_speed(sp);
                }}
                break;
              }}}}
"""
    r+="            }"
    return r

def gen_controls(d):
    rl="light:\n"; rf="fan:\n"; rs="sensor:\n"; rb="binary_sensor:\n"
    for x in d:
        n=x['name'].lower(); m=x['mac']
        rl+=f"""  - platform: midea_light
    name: "{x['name']} Light"
    id: {n}_light
    mac: "{m}"
    icon: mdi:ceiling-light
"""
        rf+=f"""  - platform: midea_fan
    name: "{x['name']} Fan"
    id: {n}_fan
    mac: "{m}"
    icon: mdi:fan
"""
        rs+=f"  - platform: template; name: \"{x['name']} Brt\"; id: {n}_brt; unit_of_measurement: \"%\"; accuracy_decimals: 0\n"
        rs+=f"  - platform: template; name: \"{x['name']} CT\"; id: {n}_ct; unit_of_measurement: \"K\"\n"
        rs+=f"  - platform: template; name: \"{x['name']} Spd\"; id: {n}_spd\n"
        rb+=f"  - platform: template; name: \"{x['name']} Light On\"; id: {n}_light_on; device_class: light\n"
        rb+=f"  - platform: template; name: \"{x['name']} Fan On\"; id: {n}_fan_on; device_class: running\n"
    rs+="  - platform: uptime; name: Uptime; update_interval: 60s\n"
    rs+="  - platform: internal_temperature; name: ESP32 Temp; unit_of_measurement: °C; accuracy_decimals: 1; update_interval: 60s\n"
    rs+="  - platform: wifi_signal; name: WiFi dBm; id: wifi_signal_db; update_interval: 60s\n"
    rs+="  - platform: copy; source_id: wifi_signal_db; name: WiFi Pct; filters: [lambda: return min(max(2*(x+100.0),0.0),100.0);]; unit_of_measurement: %; accuracy_decimals: 0\n"
    rb+="  - platform: status; name: Gateway Online; device_class: connectivity\n"
    return rl+"\n"+rf+"\n"+rs+"\n"+rb

def gen_footer():
    return """
text_sensor:
  - platform: template; name: Build Time; lambda: 'return {"${build_time}"};'; update_interval: 3600s
  - platform: version; name: ESPHome Ver; hide_timestamp: true
  - platform: wifi_info; ip_address: { name: ESP IP }; ssid: { name: ESP SSID }
button:
  - platform: restart; name: Restart GW; icon: mdi:restart; entity_category: diagnostic
"""

def main():
    c=load_devices(); d=c['devices']
    y=gen_header(c)+gen_globals(d)+gen_mqtt(c,d)+gen_ble(d)+gen_controls(d)+gen_footer()
    with open("ble_gateway.yaml","w") as f: f.write(y)
    print(f"Done: {len(d)} devices")

if __name__=="__main__": main()
