#!/usr/bin/env python3
"""美的风扇灯 ESPHome 配置生成器"""
import json

def load_devices():
    with open("devices.json", "r", encoding="utf-8") as f:
        return json.load(f)

def gen_header(c):
    return f"""# Auto-generated by generate.py
substitutions:
  project_name: "{c['project_name']}"
  build_time: "Unknown"

esphome:
  name: ble-2
  friendly_name: "${{project_name}}"
  includes:
    - midea_ble_controller.h

esp32:
  board: esp32dev
  flash_size: 4MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_BT_ENABLED: y
      CONFIG_BT_BLE_ENABLED: y

logger:
  baud_rate: 0
  level: INFO

wifi:
  ssid: "{c['wifi_ssid']}"
  password: "{c['wifi_password']}"
  fast_connect: true
  power_save_mode: none
  ap:
    ssid: "BLE-GW Fallback"
    password: "12345678"

captive_portal:
web_server:
  port: 80
ota:
  - platform: esphome
api:
  reboot_timeout: 0s
  services:
    - service: send_raw_hex
      variables:
        hex_data: string
      then:
        - lambda: 'id(tx).send_hex(hex_data);'

external_components:
  - source:
      type: local
      path: components

ble_tx:
  id: tx

esp32_ble:
  io_capability: none
  enable_on_boot: true

bluetooth_proxy:
  active: true
  cache_services: true
"""

def gen_globals(devices):
    lines = ["globals:"]
    for d in devices:
        name = d['name'].lower()
        lines.append(f"  - id: {name}_ct_kelvin")
        lines.append("    type: int")
        lines.append("    restore_value: no")
        lines.append("    initial_value: '4600'")
    return "\n".join(lines)

def gen_mqtt(config, devices):
    mqtt_template = """mqtt:
  id: bemfa
  broker: bemfa.com
  port: 9501
  username: "{uid}"
  password: "{uid}"
  client_id: "{uid}"
  keepalive: 30s
  discovery: false
  birth_message:
  will_message:
  on_message:
{topics}
"""
    topic_tpl_light = """    - topic: "{topic}"
      then:
        - lambda: |-
{light_code}
"""
    topic_tpl_fan = """    - topic: "{topic}"
      then:
        - lambda: |-
{fan_code}
"""

    light_code_tpl = """            if(x=="on"){{ int ct=id({name}_ct_kelvin),brt=id({name}_brt).state; if(brt<1)brt=50; id(tx).send_hex(midea_light_on("{mac}",brt,ct)); id({name}_light_on).publish_state(true); }}
            else if(x=="off"){{ id(tx).send_hex(midea_light_off("{mac}")); id({name}_light_on).publish_state(false); }}
            else if(x.find("on#")==0){{ auto r=x.substr(3); auto p=r.find('#'); int brt=std::stoi(r.substr(0,p)),ct=id({name}_ct_kelvin);
              if(p!=std::string::npos){{ auto s=r.substr(p+1); if(!s.empty()){{ int pc=std::stoi(s); if(pc>=2700&&pc<=6500){{ct=pc;id({name}_ct_kelvin)=ct;}}}}}}
              id(tx).send_hex(midea_light_on("{mac}",brt,ct)); id({name}_light_on).publish_state(true); }}"""

    fan_code_tpl = """            if(x=="on"){{ int spd=id({name}_spd).state; if(spd<1)spd=1; id(tx).send_hex(midea_fan_on("{mac}",spd)); id({name}_fan_on).publish_state(true); }}
            else if(x=="off"){{ id(tx).send_hex(midea_fan_off("{mac}")); id({name}_fan_on).publish_state(false); }}
            else if(x.find("on#")==0){{ int s=std::stoi(x.substr(3)); id(tx).send_hex(midea_fan_on("{mac}",s)); id({name}_fan_on).publish_state(true); }}"""

    topics = []
    for d in devices:
        name = d['name'].lower()
        mac = d['mac']
        lt = d['bemfa_light_topic']
        ft = d['bemfa_fan_topic']

        light_code = light_code_tpl.format(name=name, mac=mac)
        topics.append(topic_tpl_light.format(topic=lt, light_code=light_code))

        fan_code = fan_code_tpl.format(name=name, mac=mac)
        topics.append(topic_tpl_fan.format(topic=ft, fan_code=fan_code))

    return mqtt_template.format(uid=config['bemfa_uid'], topics="\n".join(topics))

def gen_ble(devices):
    ble_header = """esp32_ble_tracker:
  scan_parameters:
    interval: 640ms
    window: 30ms
    active: false
  on_ble_advertise:
    - then:
        - lambda: |-
            auto datas=x.get_manufacturer_datas();
            for(auto&data:datas){auto&raw=data.data; if(raw.size()<20)continue;
"""
    ble_footer = """            }"""

    device_tpl = """              uint8_t {name}_mac[6]={{{mac_bytes}}};
              for(int i=2;i<=(int)raw.size()-6;i++){{ if(memcmp(&raw[i],{name}_mac,6)==0){{
                bool lo=(raw[i+7]==0x01); int br=(int)(raw[i+12]/255.0f*100.0f);
                int ct=2700+(6500-2700)*(int)(raw[i+13]/255.0f*100.0f)/100;
                uint8_t fs=raw[i+16]; bool fr=(fs&0x01)!=0; int sp=fr?(raw[i+17]+1):0;
                static bool {name}_ll=false,{name}_lfr=false; static int {name}_lb=-1,{name}_lc=-1,{name}_lfs=-1;
                static uint32_t {name}_lr=0,{name}_lch=0; static uint8_t {name}_rc=0;
                bool ch=(lo!={name}_ll)||(br!={name}_lb)||(ct!={name}_lc)||(fr!={name}_lfr)||(sp!={name}_lfs);
                if(ch){{{name}_lch=millis();{name}_rc=0;{name}_ll=lo;{name}_lb=br;{name}_lc=ct;{name}_lfr=fr;{name}_lfs=sp;}}
                bool hb=(millis()-{name}_lr>60000),rt=(millis()-{name}_lch<10000)&&({name}_rc<3)&&(millis()-{name}_lr>3000);
                if(ch||hb||rt){{ if(rt){name}_rc++;else {name}_rc=0; {name}_lr=millis();
                  if(lo)id(bemfa).publish("{lt}/up","on#"+std::to_string(br)+"#"+std::to_string(ct));
                  else id(bemfa).publish("{lt}/up","off");
                  if(fr)id(bemfa).publish("{ft}/up","on#"+std::to_string(sp));
                  else id(bemfa).publish("{ft}/up","off");
                  id({name}_light_on).publish_state(lo); id({name}_brt).publish_state(br);
                  id({name}_ct).publish_state(ct); id({name}_fan_on).publish_state(fr);
                  id({name}_spd).publish_state(sp);
                }}
                break;
              }}}}"""

    devices_code = []
    for d in devices:
        name = d['name'].lower()
        mac = d['mac']
        mac_bytes = ", ".join([f"0x{mac[i:i+2]}" for i in range(0, 12, 2)])
        lt = d['bemfa_light_topic']
        ft = d['bemfa_fan_topic']
        devices_code.append(device_tpl.format(name=name, mac_bytes=mac_bytes, lt=lt, ft=ft))

    return ble_header + "\n".join(devices_code) + "\n" + ble_footer

def gen_controls(devices):
    light_lines = ["light:"]
    fan_lines = ["fan:"]
    sensor_lines = ["sensor:"]
    binary_lines = ["binary_sensor:"]

    for d in devices:
        name = d['name'].lower()
        mac = d['mac']
        friendly = d['name']

        light_lines.append(f"  - platform: midea_light")
        light_lines.append(f"    name: \"{friendly} Light\"")
        light_lines.append(f"    id: {name}_light")
        light_lines.append(f"    mac: \"{mac}\"")
        light_lines.append(f"    icon: mdi:ceiling-light")

        fan_lines.append(f"  - platform: midea_fan")
        fan_lines.append(f"    name: \"{friendly} Fan\"")
        fan_lines.append(f"    id: {name}_fan")
        fan_lines.append(f"    mac: \"{mac}\"")
        fan_lines.append(f"    icon: mdi:fan")

        sensor_lines.append(f"  - platform: template")
        sensor_lines.append(f"    name: \"{friendly} Brt\"")
        sensor_lines.append(f"    id: {name}_brt")
        sensor_lines.append(f"    unit_of_measurement: \"%\"")
        sensor_lines.append(f"    accuracy_decimals: 0")

        sensor_lines.append(f"  - platform: template")
        sensor_lines.append(f"    name: \"{friendly} CT\"")
        sensor_lines.append(f"    id: {name}_ct")
        sensor_lines.append(f"    unit_of_measurement: \"K\"")

        sensor_lines.append(f"  - platform: template")
        sensor_lines.append(f"    name: \"{friendly} Spd\"")
        sensor_lines.append(f"    id: {name}_spd")

        binary_lines.append(f"  - platform: template")
        binary_lines.append(f"    name: \"{friendly} Light On\"")
        binary_lines.append(f"    id: {name}_light_on")
        binary_lines.append(f"    device_class: light")

        binary_lines.append(f"  - platform: template")
        binary_lines.append(f"    name: \"{friendly} Fan On\"")
        binary_lines.append(f"    id: {name}_fan_on")
        binary_lines.append(f"    device_class: running")

    # 公共传感器
    sensor_lines.append("  - platform: uptime")
    sensor_lines.append("    name: Uptime")
    sensor_lines.append("    update_interval: 60s")
    sensor_lines.append("  - platform: internal_temperature")
    sensor_lines.append("    name: ESP32 Temp")
    sensor_lines.append("    unit_of_measurement: \"°C\"")
    sensor_lines.append("    accuracy_decimals: 1")
    sensor_lines.append("    update_interval: 60s")
    sensor_lines.append("  - platform: wifi_signal")
    sensor_lines.append("    name: WiFi dBm")
    sensor_lines.append("    id: wifi_signal_db")
    sensor_lines.append("    update_interval: 60s")
    sensor_lines.append("  - platform: copy")
    sensor_lines.append("    source_id: wifi_signal_db")
    sensor_lines.append("    name: WiFi Pct")
    sensor_lines.append("    filters:")
    sensor_lines.append("      - lambda: return min(max(2*(x+100.0),0.0),100.0);")
    sensor_lines.append("    unit_of_measurement: \"%\"")
    sensor_lines.append("    accuracy_decimals: 0")

    binary_lines.append("  - platform: status")
    binary_lines.append("    name: Gateway Online")
    binary_lines.append("    device_class: connectivity")

    return "\n".join(light_lines) + "\n" + "\n".join(fan_lines) + "\n" + "\n".join(sensor_lines) + "\n" + "\n".join(binary_lines)

def gen_footer():
    return """
text_sensor:
  - platform: template
    name: Build Time
    lambda: 'return {"${build_time}"};'
    update_interval: 3600s
  - platform: version
    name: ESPHome Ver
    hide_timestamp: true
  - platform: wifi_info
    ip_address:
      name: ESP IP
    ssid:
      name: ESP SSID

button:
  - platform: restart
    name: Restart GW
    icon: mdi:restart
    entity_category: diagnostic
"""

def main():
    config = load_devices()
    devices = config['devices']

    yaml_content = (
        gen_header(config) +
        gen_globals(devices) +
        gen_mqtt(config, devices) +
        gen_ble(devices) +
        gen_controls(devices) +
        gen_footer()
    )

    with open("ble_gateway.yaml", "w", encoding="utf-8") as f:
        f.write(yaml_content)

    print(f"Done: {len(devices)} devices")

if __name__ == "__main__":
    main()
